spring:
  application:
    name: task-common
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/testdb;LOCK_TIMEOUT=10000
    username: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql

server:
  servlet:
    encoding:
      charset: UTF-8

springdoc:
  swagger-ui:
    path: /lecture/swagger.html
    doc-expansion: none
    defaultModelsExpandDepth: -1
    groups-order: ASC
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json