spring:
  application:
    name: task-common
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/testdb
    username: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql

server:
  servlet:
    encoding:
      charset: UTF-8